import random
from datetime import datetime, timedelta
import string
from faker import Faker
from fake_useragent import UserAgent

fake = Faker(['en_US', 'fr_FR', 'es_ES'])


events_additional = [
    'Tech Innovations Expo',
    'Global Software Forum',
    'AI Tools Showcase',
    'Next-Gen Developers Summit',
    'Smart Devices Conference',
    'Cloud Architecture Forum',
    'Big Data Strategy Day',
    'Green Tech Expo',
    'Digital Products Festival',
    'Future Internet Congress',
    'Smart Manufacturing Forum',
    'Bioinformatics Discovery Day',
    'Creative Startup Week',
    'Product Design Expo',
    'Agile Methods Conference',
    'Data Visualization Marathon',
    'AI Engineering Bootcamp',
    'Science & Technology Expo',
    'Business Intelligence Forum',
    'Neural Networks Symposium',
    'IoT Systems Summit',
    'Serverless Architecture Day',
    'Mobile Apps Hackathon',
    'Innovation Management Forum',
    'Urban Innovation Day',
    'Cloud Security Conference',
    'Future Retail Summit',
    'IT Infrastructure Meetup',
    'Digital Culture Forum',
    'SaaS Growth Conference',
    'Tech Mentors Meetup',
    'Startup Development Forum',
    '3D Modeling Workshop',
    'Digital Media Festival',
    'AI Automation Forum',
    'Environmental Tech Day',
    'Sustainable Business Expo',
    'Education & Science Forum',
    'Machine Vision Conference',
    'Cognitive Tech Meetup',
    'Tech Creators Lab',
    'Product Discovery Day',
    'Creative Studio Weekend',
    'Design Thinking Masterclass',
    'Digital Skills Workshop',
    'Green Cities Forum',
    'Blockchain Engineering Meetup',
    'Tech Marketing Summit',
    'Future Enterprises Expo',
    'Advanced Robotics Summit',
    'Digital Broadcast Conference',
    'Biotech Discovery Forum',
    'Future Energy Expo',
    'Wellbeing & Lifestyle Festival',
    'Creative Solutions Conference',
    'Open Innovation Forum',
    'Health Analytics Day',
    'Tech Community Meetup',
    'New Media Expo',
    'Urban Solutions Summit',
    'Knowledge Sharing Week',
    'AI Business Day',
    'Startup Operations Workshop',
    'Engineering Innovations Expo',
    'Future Technologies Forum',
    'Digital Skills Festival',
    'Product Architecture Day',
    'IT Strategy Summit',
    'Smart Solutions Conference',
    'Tech Transformation Forum',
    'UX Trends Festival',
    'Robotics Lab Day',
    'Science & Innovation Forum',
    'Creative Lab Weekend',
    'Technology Leaders Day',
    'Digital Discovery Summit',
    'Cloud Innovation Conference',
    'IT Analytics Forum',
    'Tech Insights Meetup',
    'Urban Mobility Forum',
    'EnergyTech Innovations Day',
    'Advanced Computing Expo',
    'AI in Business Forum',
    'Young Innovators Festival',
    'Future Learning Expo',
    'Design Pro Summit',
    'Intelligent Systems Conference',
    'Tech Experience Day',
    'Sustainable Innovation Forum',
    'AI in Education Summit',
    'Next-Gen Creators Meetup',
    'Digital Communication Expo',
    'Startup Mastery Bootcamp',
    'Engineering Hackathon',
    'Tech Art Expo',
    'Smart Industry Forum',
    'Global Creativity Summit',
    'Digital Business Expo',
    'Future Industry Expo',
    'Tech Vision Summit',
    'AI Applications Forum',
    'Digital Innovation Day',
    'Smart Tech Symposium',
    'Next-Gen Solutions Expo',
    'Deep Tech Conference',
    'Creative Innovation Lab',
    'Product Evolution Forum',
    'New Technologies Summit',
    'Innovation Acceleration Day',
    'Tech Growth Congress',
    'AI Integration Workshop',
    'Digital Platforms Expo',
    'Smart Workspaces Forum',
    'Design & Technology Summit',
    'Intelligent Automation Expo',
    'Future Creators Forum',
    'Tech Innovation Marathon',
    'Engineering Systems Day',
    'Digital Transformation Forum',
    'Automation Strategy Conference',
    'Creative Engineering Expo',
    'Future Systems Symposium',
    'AI Strategy Conference',
    'Tech Innovation Festival',
    'Sustainable Tech Forum',
    'Digital Engineering Day',
    'Tech Advancement Summit',
    'Global Innovation Exchange',
    'AI Research Forum',
    'Digital Workflow Conference',
    'Next-Level Development Expo',
    'Creative Solutions Lab',
    'Smart Data Conference',
    'Digital Mindset Forum',
    'Tech Talent Expo',
    'Future Solutions Day',
    'AI & Data Forum',
    'Innovation Leaders Meetup',
    'Creative Tech Forum',
    'Next-Gen Interfaces Expo',
    'Tech Progress Summit',
    'Digital Intelligence Day',
    'Engineering Mastery Forum',
    'Tech Discovery Expo',
    'AI & Cloud Forum',
    'Innovation Culture Conference',
    'Advanced Technologies Day',
        "Digital Innovation Summit",
    "Tech Evolution Forum",
    "Smart Technologies Expo",
    "AI Development Congress",
    "Future Software Expo",
    "Robotics Engineering Forum",
    "Intelligent Data Expo",
    "Applied Technologies Summit",
    "Next-Gen IT Forum",
    "Tech Integration Expo",
    "Global AI Innovation Day",
    "Cloud Systems Week",
    "Big Data Engineering Forum",
    "Smart Automation Expo",
    "AI Tools Day",
    "Intelligent Architecture Summit",
    "Tech Leadership Forum",
    "Future Engineering Expo",
    "Cyber Systems Conference",
    "Advanced IT Solutions Day",
    "AI Optimization Summit",
    "Cloud Platforms Forum",
    "Intelligent Devices Expo",
    "Digital Systems Congress",
    "Software Innovation Day",
    "Smart Cities Technology Expo",
    "High-Tech Engineering Summit",
    "Machine Intelligence Forum",
    "Global Tech Engineering Day",
    "Smart Computing Congress",
    "IT Process Optimization Forum",
    "Digital Engineering Marathon",
    "Innovation Tech Camp",
    "Software Architecture Expo",
    "Intelligent Robotics Day",
    "High-Performance Computing Forum",
    "Smart Analytics Summit",
    "System Design Expo",
    "Technology Strategy Forum",
    "IT Management Congress",
    "Software Development Expo",
    "Tech Engineering Festival",
    "Automation Engineering Summit",
    "Data Systems Expo",
    "Future Devices Forum",
    "Smart Solutions Marathon",
    "Engineering Discovery Day",
    "AI Engineering Forum",
    "Intelligent Cloud Day",
    "Computing Innovations Summit",
    "Digital Architecture Expo",
    "Software Systems Congress",
    "Tech Product Day",
    "System Innovations Expo",
    "Cloud Technologies Marathon",
    "High-Tech Strategy Forum",
    "Digital Products Lab",
    "Computing Vision Forum",
    "AI Research Day",
    "Robotics Solutions Expo",
    "Technology Discovery Week",
    "Smart Platforms Summit",
    "Advanced Software Congress",
    "Tech Intelligence Day",
    "Data Innovation Forum",
    "Next-Level Tech Expo",
    "Engineering Transformation Summit",
    "Intelligent Manufacturing Forum",
    "Future Computing Expo",
    "Digital Strategy Forum",
    "Applied IT Engineering Day",
    "Tech Integration Congress",
    "Software Intelligence Expo",
    "Data Engineering Summit",
    "Smart Architecture Forum",
    "IT Innovation Marathon",
    "Intelligent Automation Day",
    "Cloud Infrastructure Forum",
    "Advanced Robotics Forum",
    "Digital Intelligence Summit",
    "Tech Operations Expo",
    "Intelligent IT Forum",
    "Computing Strategy Day",
    "AI Systems Expo",
    "Digital Solutions Festival",
    "Smart Technologies Summit",
    "Software Growth Forum",
    "Intelligent Systems Expo",
    "Engineering Intelligence Day",
    "Tech Discovery Summit",
    "Applied Innovation Forum",
    "Next-Gen Data Expo",
    "Digital Experience Forum",
    "AI Transformation Day",
    "IT Engineering Evolution Summit",
    "Intelligent Tech Congress",
    "Computing Discovery Expo",
    "Future Platforms Forum",
    "Digital Systems Expo",
    "Advanced Data Summit",
    "Tech Development Marathon",
    "Automated Solutions Expo",
    "Cloud Innovation Day",
    "Smart Data Summit",
    "Engineering Solutions Forum",
    "Software Transformation Day",
    "Future Analytics Expo",
    "Intelligent Tech Lab",
    "Digital Engineering Forum",
    "High-Tech Development Summit",
    "Smart Industry Conference",
    "System Architecture Forum",
    "AI Technologies Marathon",
    "Tech System Summit",
    "Digital Platforms Forum",
    "Intelligent Development Expo",
    "Future Robotics Day",
    "Advanced Cloud Solutions Expo",
    "Smart Data Engineering Forum",
    "Computing Integration Summit",
    "Software Evolution Forum",
    "Innovation Discovery Expo",
    "Digital Research Day",
    "Intelligent Code Summit",
    "Applied Cloud Conference",
    "Machine Systems Forum",
    "Tech Vision Day",
    "Engineering Technologies Expo",
    "Smart Computing Day",
    "AI Product Forum",
    "Data Intelligence Expo",
    "Next-Gen Architecture Summit",
    "Future Automation Expo",
    "Software Research Forum",
    "Intelligent Code Expo",
    "Tech Progress Day",
    "Advanced Computing Marathon",
    "IT Discovery Forum",
    "Digital Product Strategy Summit",
    "Engineering Design Expo",
    "Intelligent Platforms Forum",
    "Smart Cloud Day",
    "Applied AI Summit",
    "Software Discovery Expo",
    "Tech Enhancement Forum",
    "Intelligent Computing Day",
    "Digital Product Lab",
    "Systems Innovation Summit",
    "IT Analytics Conference",
    "Smart Engineering Expo",
    "Applied Tech Summit",
    "High-Tech Solutions Expo",
    "Future Strategy Forum",
    "Digital Optimization Day",
    "Intelligent Devices Forum",
    "Systems Development Marathon",
    "Advanced Innovation Expo",
    "Tech Architecture Forum",
    "Computing Growth Summit",
    "Digital Manufacturing Day",
    "Smart Architecture Summit",
    "Applied Data Engineering Day",
    "Intelligent Systems Congress",
    "Software Advancement Forum",
    "Digital Tools Expo",
    "AI Engineering Camp",
    "Future Technology Day",
    "High-Tech Product Forum",
    "Engineering Data Summit",
    "Intelligent Manufacturing Day",
    "Tech Productivity Expo",
    "Digital Platforms Marathon",
    "Smart Innovation Forum",
    "Applied Computing Day",
    "Software Systems Festival",
    "Intelligent Infrastructure Summit",
    "IT Development Expo",
    "Automation Process Day",
    "Digital Evolution Forum",
    "AI Discovery Festival",
    "Smart Cloud Systems Expo",
    "High-Tech Enterprise Summit",
    "Digital Efficiency Forum",
    "Data Systems Day",
    "Applied Robotics Summit",
    "Tech Project Expo",
    "Intelligent Cloud Systems Day",
    "Engineering Products Forum",
    "Future Data Expo",
    "Digital Competence Summit",
    "AI Data Systems Forum",
    "Smart Industry Engineering Day",
    "Next-Gen Cloud Expo",
    "Applied Systems Summit",
    "Innovation Management Expo",
    "Intelligent Innovation Day",
    "Future Devices Expo",
    "Engineering Analytics Summit",
    "Smart Computing Forum",
    "Digital Optimization Expo",
    "Advanced Tech Solutions Forum",
    "Intelligent Robotics Summit",
    "Data Platforms Day",
    "Computing Optimization Expo",
    "Software Performance Summit",
    "Digital Architectures Forum",
    "AI Productivity Day",
    "Smart Engineering Research Expo",
    "Applied Intelligence Forum",
    "Innovative Development Summit",
    "Digital Systems Lab",
    "Tech Engineering Congress",
    "Software Platforms Forum",
    "Intelligent Solutions Day",
    "High-Tech Research Expo",
    "Digital Efficiency Summit",
    "AI and Data Day",
    "Smart Software Engineering Expo",
    "Future Computing Symposium",
    "Intelligent Strategy Forum",
    "Cloud Development Day",
    "Applied IT Conference",
    "Tech Engineering Lab",
    "Future Innovation Day",
    "Digital Research Summit",
    "Intelligent Robotics Expo",
    "High-Tech Data Forum",
    "Smart Solutions Day",
    "Applied Development Summit",
    "Digital Progress Expo",
    "Computing Intelligence Forum",
    "Software Methodology Day",
    "Intelligent Data Systems Summit",
    "Tech Discovery Lab",
    "Digital Operations Forum",
    "Cloud Intelligence Day",
    "Engineering Software Expo",
    "Smart Platforms Day",
    "IT Strategy Engineering Forum",
    "Future Software Engineering Day",
    "AI Innovation Marathon",
    "Digital Engineering Symposium",
    "Smart Development Summit",
    "High-Tech Vision Forum",
    "Applied Innovation Lab",
    "Intelligent Tech Expo",
    "Digital Data Forum",
    "Smart Industry Day",
    "Engineering Cloud Summit",
    "IT Optimization Expo",
    "Future Data Technologies Forum",
    "Intelligent Automation Day",
    "Advanced Industry Expo",
    "Digital Productivity Forum",
    "Software Platforms Day",
    "Smart Innovation Lab",
    "Tech Engineering Day",
    "Cloud Integration Expo",
    "High-Tech Architecture Forum",
    "Intelligent Products Summit",
    "Digital Analytics Day",
    "Future Engineering Congress",
    "Applied Systems Innovation Day",
    "Software Performance Forum",
    "Smart Data Lab",
    "Next-Gen Computing Summit",
    "Digital Intelligence Expo",
    "Tech Optimization Forum",
    "Smart Cloud Engineering Day",
    "Engineering Intelligence Expo",
    "Applied Robotics Innovation Day",
    "Software Strategy Summit",
    "Intelligent Tech Solutions Expo",
    "Digital Transformation Day",
    "Cloud Strategy Forum",
    "High-Tech Solutions Summit",
    "Smart Data Systems Day",
    "Applied Technology Lab",
    "Intelligent Engineering Congress",
    "Digital Code Forum",
    "System Optimization Day",
    "AI Tools Expo",
    "Smart Infrastructure Summit",
    "Tech Operations Forum",
    "Digital Security Day",
    "Future Tech Engineering Expo",
    "Applied Data Summit",
    "Intelligent Computing Conference",
    "High-Tech Innovation Day",
    "Digital Software Expo",
    "Smart Automation Forum",
    "Tech Strategy Lab",
    "Computing Performance Summit",
    "Intelligent Cloud Expo",
    "Digital Research Forum",
    "Applied Engineering Systems Day",
    "Future Intelligence Expo",
    "Tech Architecture Day",
    "Digital Product Engineering Forum",
    "Smart Data Innovations Expo"
]

mail_domains = ['gmail.com', 'outlook.com', 'mail.ru']

priority_list = ['Low', 'Medium', 'High', 'Critical']

ua = UserAgent()


def random_title():
    return random.choice(events_additional)


def random_date():
    start = datetime(2025, 12, 8)
    end = datetime(2026, 12, 31)

    delta = end - start
    random_days = random.randint(0, delta.days)

    result = start + timedelta(days=random_days)
    return result.strftime('%Y-%m-%d')


def random_date_until(end_date: str) -> str:
    start = datetime(2025, 12, 8)
    end = datetime.strptime(end_date, '%Y-%m-%d')

    if start > end:
        raise ValueError("start_date не может быть позже end_date")
    
    delta_days = (end - start).days
    random_days = random.randint(0, delta_days)
    
    random_date = start + timedelta(days=random_days)
    return random_date.strftime('%Y-%m-%d')


def random_time():
    hour = random.randint(0, 23)
    minute = random.randint(0, 59)
    return f'{hour:02d}:{minute:02d}'


def get_creds():
    chars = string.ascii_letters + string.digits + '!@#$%^&*()_-+=[]{}'
    length = random.randint(6, 8)
    
    username = fake.name()
    password = ''.join(random.choice(chars) for _ in range(length))
    return username.replace('-', ' '), password


def get_priority():
    return random.choice(priority_list)


def get_user_agent():
    return ua.random


def get_random_domain():
    return random.choice(mail_domains)